Repository ICOMP-UNC/Bit-Masters, pull requests merged in 2024-11, with the labels that each got.

#5 [FEATURE][#2] Create GPIO Configuration
  include/configuration.h
  src/configuration.c
Labels: enhancement, task

#6 Added I2C Configuration
  include/configuration.h
  src/configuration.c
Labels: enhancement, epic, task

#9 configuration of the adc
  include/configuration.h
  src/configuration.c
Labels: enhancement, task

#7 [FEATURE][#3] Create PWM Configuration
  include/configuration.h
  src/configuration.c
Labels: enhancement, task

#10 Add Core Configuration and Project Structure for STM32
  .clang-format
  .gitignore
  Doxyfile
  include/README
  include/configuration.h
  lib/README
  platformio.ini
  src/configuration.c
  test/README
Labels: enhancement, epic, task

#16 Add main.c with task management, FreeRTOS setup, and hardware configuration
  include/configuration.h
  lib/rtos/FreeRTOSConfig.h
  lib/rtos/include/FreeRTOS.h
  lib/rtos/include/StackMacros.h
  lib/rtos/include/atomic.h
  lib/rtos/include/croutine.h
  lib/rtos/include/deprecated_definitions.h
  lib/rtos/include/event_groups.h
  lib/rtos/include/list.h
  lib/rtos/include/message_buffer.h
  lib/rtos/include/mpu_prototypes.h
  lib/rtos/include/mpu_wrappers.h
  lib/rtos/include/portable.h
  lib/rtos/include/portmacro.h
  lib/rtos/include/projdefs.h
  lib/rtos/include/queue.h
  lib/rtos/include/semphr.h
  lib/rtos/include/stack_macros.h
  lib/rtos/include/stream_buffer.h
  lib/rtos/include/task.h
  lib/rtos/include/timers.h
  lib/rtos/portable/stm32/port.c
  lib/rtos/source/croutine.c
  lib/rtos/source/event_groups.c
  lib/rtos/source/heap_4.c
  lib/rtos/source/list.c
  lib/rtos/source/mpu_wrappers.c
  lib/rtos/source/queue.c
  lib/rtos/source/stream_buffer.c
  lib/rtos/source/tasks.c
  lib/rtos/source/timers.c
  lib/rtos/stdint.h
  src/main.c
Labels: enhancement, task, great_code

#17 [FEATURE][#2] Handlers interruptions
  include/configuration.h
  src/configuration.c
  src/main.c
Labels: enhancement, task

#14 [FEATURE][#2] Open and close door functions
  include/configuration.h
  include/system_response.h
  src/configuration.c
  src/system_response.c
Labels: enhancement, task

#11 Added system response functionality for temperature and PWM control
  include/configuration.h
  include/system_response.h
  src/system_response.c
Labels: enhancement, epic, great_code

#13 [FEATURE][#2] Show temperature in display
  include/alarm.h
  src/alarm.c
  src/configuration.c
Labels: enhancement, task

#12 [FEATURE][#2] Read battery ADC value
  include/alarm.h
  include/configuration.h
  src/alarm.c
Labels: enhancement, task

#19 Revert "Alarm and notification"
  include/alarm.h
  include/configuration.h
  src/alarm.c
  src/configuration.c
Labels: bug, invalid, wontfix

#21 Revert "Alarm and notification"
  include/alarm.h
  include/configuration.h
  src/alarm.c
  src/configuration.c
Labels: bug, invalid, wontfix

#22 Alarm and notification
  include/alarm.h
  include/configuration.h
  src/alarm.c
  src/configuration.c
Labels: enhancement, epic, task, great_code

#23 Add System Response Functions for Alarm, Temperature Display, Door Control, and Motor PWM
  include/alarm_and_notifications.h
  include/configuration.h
  include/system_response.h
  src/alarm_and_notifications.c
  src/configuration.c
  src/system_response.c
Labels: enhancement, epic, task, great_code

#26 Add QA Workflow with Style, Documentation, and Build Checks
  .github/.keep
  .github/actions/build/action.yml
  .github/actions/document/action.yml
  .github/actions/style/action.yml
  .github/workflows/Workflow.yml
Labels: enhancement, epic
